kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
    app.kubernetes.io/instance: myapp
  name: nginx-deployment
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30500
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
